ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL
  - YAML_YAMLLINT

# Helm templates contain {{ }} syntax that is not valid YAML
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (charts/quibble/templates)

FILTER_REGEX_EXCLUDE: (megalinter-reports|\.git)

GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true

APPLY_FIXES: none
