ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - JSON_JSONLINT
  - KUBERNETES_HELM
  - KUBERNETES_KUBECONFORM
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - SPELL_CSPELL

FILTER_REGEX_EXCLUDE: (megalinter-reports|\.git)

GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true

APPLY_FIXES: none
