apiVersion: v2
name: quibble
description: Self-hosted Kubernetes trivia platform. Includes the API, web frontend, and Redis.
type: application
version: 0.1.0
appVersion: "1.2.0"
keywords:
  - trivia
  - quiz
  - game
home: https://github.com/benbotsford/trivia
sources:
  - https://github.com/benbotsford/trivia
maintainers:
  - name: benbotsford
    url: https://github.com/benbotsford
