apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quibble.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quibble.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "api.secret.databaseUrl is required" .Values.api.secret.databaseUrl | quote }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  AUTH0_SECRET: {{ required "web.secret.auth0Secret is required" .Values.web.secret.auth0Secret | quote }}
  AUTH0_CLIENT_SECRET: {{ required "web.secret.auth0ClientSecret is required" .Values.web.secret.auth0ClientSecret | quote }}
