apiVersion: v1
kind: Service
metadata:
  name: {{ include "quibble.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quibble.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "quibble.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
